module.exports = {
  responseDefault: {
    CREATED_DATA: 'DATA BERHASIL DITAMBAHKAN',
    DATA_EXIST: 'DATA SUDAH TERDAFTAR',
    ID_NOTFOUND: 'ID TIDAK DITEMUKAN',
    DELETE_DATA: 'DATA BERHASIL DIHAPUS',
    UPDATE_DATA: 'DATA BERHASIL DI UPDATE',
  },
};
